
package:
  name: pwspy
  version: {{ environ['GIT_DESCRIBE_TAG'] + '.' + environ.get('GIT_DESCRIBE_NUMBER', '')  }}

source:
  path: .. #tells conda-build that the source code is in the parent directory.

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{environ['GIT_DESCRIBE_HASH']}}
  entry_points:
    - PWSAnalysis = pwspy.apps.PWSAnalysisApp.__main__:main   # We must have an entry point specified for each entry point in setup.py or the noarch conda build will fail.
    - ERCreator = pwspy.apps.ExtraReflectanceCreator.__main__:main

requirements:
  build:
    - python >=3.7
    - setuptools
    - gitpython

  run:
    - python >=3.7
    - numpy >=1.16
    - scipy >=0.18
    - tifffile
    - psutil
    - shapely
    - h5py
    - pandas
    - matplotlib >=1.4
    - jsonschema
    - google-api-python-client 
    - google-auth-httplib2
    - google-auth-oauthlib
    - opencv =4
    - pyqt =5
    - scikit-image
    - mpl_qt_viz >=1.0.5  # Plotting package available on PyPi and the backmanlab anaconda cloud account. Written for this project by Nick Anthony

app:
  entry: PWSAnalysis
  icon: cellLogo64.png  #The logo doesn't work :(
  summary: PWS Analysis GUI
  type: desk
  own_environment: False

about:
  home: https://bitbucket.org/backmanlab/pwspython/src/master/
  summary: "A framework for working with Partial Wave Spectroscopy files."
  description: "A framework for working with Partial Wave Spectroscopy files."
  doc_url: https://pwspy.readthedocs.io/en/dev/
  dev_url: https://bitbucket.org/backmanlab/pwspython/src/master/
  
