{% set data = load_setup_py_data() %}

package:
  name: pwspy
  version: {{ environ['GIT_DESCRIBE_TAG'] + '.' + environ.get('GIT_DESCRIBE_NUMBER', '')  }}

source:
  path: ..

build:
  number: 0
  string: {{environ['GIT_DESCRIBE_HASH']}}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.16
    - scipy >=0.18
    - tifffile # -c conda-forge
    - psutil
    - shapely
    - h5py
    - pandas
    - matplotlib >=1.4
    - jsonschema
    - google-api-python-client # -c conda-forge
    - google-auth-httplib2 # -c conda-forge
    - google-auth-oauthlib # -c conda-forge
    - py-opencv

about:
  home: data['url']

  summary: data['description']
  description: data['long_description']
  dev_url: data['url']