
package:
  name: pwspy
  version: {{ environ['GIT_DESCRIBE_TAG'] + '.' + environ.get('GIT_DESCRIBE_NUMBER', '')  }}

source:
  path: .. #tells conda-build that the source code is in the parent directory.

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{environ['GIT_DESCRIBE_HASH']}}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python #We seem to only be compatible with python 3.7 right now. can't specify here.
    - numpy >=1.16
    - scipy >=0.18
    - tifffile # -c conda-forge
    - psutil
    - shapely
    - h5py
    - pandas
    - matplotlib >=1.4
    - jsonschema
    - google-api-python-client # -c conda-forge
    - google-auth-httplib2 # -c conda-forge
    - google-auth-oauthlib # -c conda-forge
    - py-opencv =3 # Version 4 is now available but doesn't seems to import the same way
    - pyqt =5

about:
  home: https://bitbucket.org/backmanlab/pwspython/src/master/
  summary: "A framework for working with Partial Wave Spectroscopy files."
  description: "A framework for working with Partial Wave Spectroscopy files."
  dev_url: https://bitbucket.org/backmanlab/pwspython/src/master/
  
app:
  entry: python -m pwspy.apps.PWSAnalysisApp
  icon: cellLogo64.png
  summary: PWS Analysis GUI
  type: desk
  own_environment: False