{% set version = load_setup_py_data().get("version") %}  # In order for this to work we must install setuptools_scm prior to running conda-build, hopefully they'll fix that.

package:
  name: pwspy
  version: {{ version }}

source:
  path: .. #tells conda-build that the source code is in the parent directory.

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.7
    - setuptools
    - setuptools_scm

  run:
    - python >=3.7
    - numpy >=1.16, <1.23
    - scipy =1.7
    - tifffile
    - psutil
    - shapely =1.8
    - h5py =3
    - pandas =1.3
    - matplotlib =3.5
    - jsonschema =4
    - opencv =4.5
    - scikit-image =0.18
    - rasterio =1

about:
  home: https://github.com/BackmanLab/PWSpy
  summary: "A framework for working with Partial Wave Spectroscopy files."
  description: "A framework for working with Partial Wave Spectroscopy files."
  doc_url: https://pwspy.readthedocs.io/en/dev/
  dev_url: https://github.com/BackmanLab/PWSpy
  
