name: Upload Anaconda Cloud

on:
  release:
    types: [created]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
         auto-activate-base: true
         activate-environment: ""
      - name: Install dependencies
        run: |
          conda install setuptools_scm conda-build anaconda-client
      - name: Build
        run: conda build . --output-folder ./condaDist   
      - name: publish-to-conda
        shell: bash -l {0}  # This is needed in order to activate the bash environment created by conda. Otherwise the `anaconda` command won't be found
        run: anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload condaDist/noarch/pwspy*
